LastBackProje/LastBackProje/Controllers/BasketController.cs
using LastBackProje.DataAccesLAyer;
using LastBackProje.Models;
using LastBackProje.ViewModels.BasketVMs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;

namespace LastBackProje.Controllers
{
    public class BasketController : Controller
    {
        private readonly AppDbContext _context;

        public BasketController(AppDbContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> CardBasket(int? id)
        {
           
            ICollection<BasketVm> basket = await _context.Products.Select(p=>new BasketVm()
            {
                Count = p.Count,
                Title = p.Title,
                ExTag=p.ExTag,

            }).ToListAsync();
            return View(basket);
        }

        public async Task<IActionResult> DeleteBasket(int ?id)
        {
            if (id == null) return BadRequest("id yanlisdir");

            if (!await _context.Products.AnyAsync(p => p.IsDeleted == false && p.Id == id)) return NotFound("not found");

            string? basket = Request.Cookies["basket"];
            List<BasketVm> basketVms = null;

           
            if (string.IsNullOrEmpty(basket))
            {
                return BadRequest("id tapilmadi");
            }

            basketVms = JsonConvert.DeserializeObject<List<BasketVm>>(basket);

            if (basketVms.Exists(b => b.Id != id))
            {
                return BadRequest("id basket icinde deyil");
            }

            basketVms.Remove(basketVms.Find(b => b.Id == id));

            basket = JsonConvert.SerializeObject(basketVms);

            Response.Cookies.Append("basket", basket);

            return PartialView("_BasketPartial", basketVms);
        }

        public async Task<IActionResult> AddBasket(int? id)
        {
            if (id == null) return BadRequest("id yanlisdir");

            if (!await _context.Products.AnyAsync(p=>p.IsDeleted==false && p.Id==id)) return NotFound("not found");

            string? basket = Request.Cookies["basket"];
            List<BasketVm> basketVms = null;

            if (!string.IsNullOrEmpty(basket))
            {
                basketVms = JsonConvert.DeserializeObject<List<BasketVm>>(basket);

                if (basketVms.Exists(b => b.Id == id))
                {
                    basketVms.Find(b => b.Id == id).Count += 1;
                }
                else
                {

                    basketVms.Add(new BasketVm
                    {
                        Id = (int)id,
                        Count = 1
                    });
                }
            }
            else
            {
                basketVms = new List<BasketVm> { new BasketVm

                        {
                             Id = (int)id,
                            Count = 1
                        }
                };
            }

            basket = JsonConvert.SerializeObject(basketVms);

            Response.Cookies.Append("basket", basket);

            foreach (BasketVm basketVm in basketVms)
            {
                Product product = await _context.Products.FirstOrDefaultAsync(p => p.Id == basketVm.Id);

                basketVm.Title = product.Title;
                basketVm.Image = product.MainImage;
                basketVm.Price = product.DisCountPrice > 0 ? product.DisCountPrice : product.Price;
                basketVm.ExTag= product.ExTag;
            }

            return PartialView("_BasketPartial", basketVms);
        }

    }
}

LastBackProje/LastBackProje/Controllers/ProductController.cs
using LastBackProje.DataAccesLAyer;
using LastBackProje.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using System.Net;

namespace LastBackProje.Controllers
{
    public class ProductController : Controller
    {
        private readonly AppDbContext _context;

        public ProductController(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            List<Product>products = await _context.Products
                .Where(p=>p.IsDeleted==false)
                .OrderByDescending(p=>p.Id)
                .Take(12)
                .ToListAsync();

            return View(products);
        }

        public async Task<IActionResult> search(string search, int? categoryid)
        {
            List<Product> products = null;

            if (categoryid != null && await _context.Categories.AnyAsync(c=>c.IsDeleted==false && c.Id == categoryid))
            {
                products = await _context.Products
               .Where(p => p.IsDeleted == false && p.CategoryId== (int)categoryid || (
               p.Title.ToLower().Contains(search.ToLower()) ||
               p.Brand != null ? p.Brand.Name.ToLower().Contains(search.ToLower()) : true)
               ).ToListAsync();
            }
            else
            {
                products = await _context.Products
                 .Where(p => p.IsDeleted == false || (
                 p.Title.ToLower().Contains(search.ToLower()) ||
                 p.Brand != null ? p.Brand.Name.ToLower().Contains(search.ToLower()) : true) ||
                 p.Category.Name.ToLower().Contains(search.ToLower())
                 ).ToListAsync();
            }

           return PartialView("_searchPartial", products);

        }


        public async Task<IActionResult> Modal(int? id)
        {
            if(id == null) return BadRequest("id yanlisdir");

            Product product =await _context.Products
                .Include(p=>p.productImages.Where(pi => pi.IsDeleted == false))
                .FirstOrDefaultAsync(p=>p.IsDeleted == false && p.Id == id);

            if(product == null) return NotFound();

            return PartialView("_ModalPartial",product);
        }

        


    }
}

LastBackProje/LastBackProje/Views/Shared/_BasketPartial.cshtml
@model IEnumerable<BasketVm>


<div class="cart-btn">
    <a asp-controller="Basket" asp-action="CardBasket" >
        <i class="icon ion-bag"></i>
        <span class="text">Cart :</span>
        <span class="total">$@Model.Sum(m=>m.Count * (m.Price + m.ExTag))</span>
        <span class="count">@Model.Count()</span>
    </a>
</div>
<div class="mini-cart">

    <ul class="cart-items">
        @foreach (BasketVm basketVm in Model)
        {
            <li>
                <div class="single-cart-item d-flex" data-product-id="@basketVm.Id">
                    <div class="cart-item-thumb">
                        <a href="single-product.html"><img src="~/assets/images/product/@basketVm.Image" alt="product"></a>
                        <span class="product-quantity">(@basketVm.Count) x</span>
                    </div>
                    <div class="cart-item-content media-body">
                        <h5 class="product-name"><a href="single-product.html">@basketVm.Title</a></h5>
                        <span class="product-price">€@basketVm.Price</span>
                        
                        <a class="product-close" asp-controller="Basket" asp-action="DeleteBasket" asp-route-id="@basketVm.Id">
                            <i class="fal fa-times"></i>
                        </a>
                    </div>
                </div>
            </li>
        }
      
    </ul>

    

    <div class="price_content">
        <div class="cart-subtotals">
            <div class="products price_inline">
                <span class="label">Subtotal</span>
                <span class="value">€@Model.Sum(m=>m.Count * m.Price)</span>
            </div>
        
            <div class="tax price_inline">
                <span class="label">Taxes</span>
                <span class="value">€@Model.Sum(m=>m.Count * m.ExTag)</span>
            </div>
        </div>
        <div class="cart-total price_inline">
            <span class="label">Total</span>
            <span class="value">€@Model.Sum(m=>m.Count * (m.Price + m.ExTag))</span>
        </div>
    </div> <!-- price content -->
    <div class="checkout text-center">
        <a href="checkout.html" class="main-btn">Checkout</a>
    </div>
</div> <!-- mini cart -->

LastBackProje/LastBackProje/Views/Shared/_ModalPartial.cshtml
@model Product

<div class="modal-header">
    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
        <i class="fal fa-times"></i>
    </button>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-md-6">
            <div class="product-quick-view-image mt-30">
                <div class="quick-view-image">

                    @if(Model.productImages !=null && Model.productImages.Count() > 0)
                    {
                        @foreach (ProductImages productImages in Model.productImages)
                        {
                            <div class="single-view-image">
                                <img src="~/assets/images/product/@productImages.Image" alt="product">
                            </div>
                        }
                    }
                  
                  
                </div>

                <ul class="quick-view-thumb">

                    @if(Model.productImages != null && Model.productImages.Count() > 0)
                    {
                        @foreach (ProductImages productImages in Model.productImages)
                        {
                            <li>
                                <div class="single-thumb">
                                    <img src="~/assets/images/product/@productImages.Image" alt="">
                                </div>
                            </li>
                        }
                    }

                   
                
                </ul>
            </div> <!-- Modal Quick View Image -->
        </div>
        <div class="col-md-6">
            <div class="product-quick-view-content mt-30">
                <h3 class="product-title">@Model.Title</h3>
                <p class="reference">Reference: demo_12</p>
                <ul class="rating">
                    <li class="rating-on"><i class="fas fa-star"></i></li>
                    <li class="rating-on"><i class="fas fa-star"></i></li>
                    <li class="rating-on"><i class="fas fa-star"></i></li>
                    <li class="rating-on"><i class="fas fa-star"></i></li>
                    <li class="rating-on"><i class="fas fa-star"></i></li>
                </ul>
                <div class="product-prices">
                    @if(Model.DisCountPrice !=null && Model.DisCountPrice > 0)
                    {
                        <span class="sale-price"> €@Model.Price</span>
                        <span class="regular-price">€@Model.DisCountPrice</span>
                        <span class="save">Save @((((Model.Price - Model.DisCountPrice) / Model.Price) * 100).ToString("#.##"))</span>
                    }
                    else
                    {
                        <span class="regular-price">€@Model.Price</span>
                    }

                        
                        
                  </div>
                <p class="product-description">@Model.SmallDescription</p>
        
                <div class="product-add-cart">
                    <button><i class="icon ion-bag"></i> Add to cart</button>
                </div>
                <div class="product-wishlist-compare">
                    <ul class="d-flex flex-wrap">
                        <li><a href="#"><i class="fal fa-heart"></i> Add to wishlist</a></li>
                        <li><a href="#"><i class="fal fa-repeat"></i> Add to compare</a></li>
                    </ul>
                </div>
                <div class="product-share d-flex">
                    <p>Share</p>
                    <ul class="social media-body">
                        <li><a href="#"><i class="fab fa-facebook-f"></i></a></li>
                        <li><a href="#"><i class="fab fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fab fa-google"></i></a></li>
                        <li><a href="#"><i class="fab fa-pinterest-p"></i></a></li>
                    </ul>
                </div>
            </div> <!-- Modal Quick View Content -->
        </div>
    </div> <!-- row -->
</div>  <!-- Modal Body -->

LastBackProje/LastBackProje/Views/Shared/_ProductListPartial.cshtml
@model IEnumerable<Product>

<div class="product-items">

    <div class="row product-active">
        @for (int i = 0; i < (int)Math.Ceiling((decimal)Model.Count() / 2); i++)
        {

            <div class="col-lg-2">

                @foreach (Product product in Model.Skip(i * 2).Take(2))
                {
                    <div class="single-product mt-30">
                        <div class="product-image">
                            <a href="single-product.html">
                                <img class="first-image" src="~/assets/images/product/@product.MainImage" alt="product">
                                <img class="second-image" src="~/assets/images/product/@product.HoverImage" alt="product">
                            </a>
                            <ul class="product-meta">
                                <li><a class="AddBasket" asp-controller="Basket" asp-action="AddBasket" asp-route-id="@product.Id"><i class="icon ion-bag"></i></a></li>
                                <li><a href="#"><i class="icon ion-android-favorite-outline"></i></a></li>
                                <li><a href="#"><i class="icon ion-android-options"></i></a></li>
                                <li><a class="modalBtn" data-toggle="modal" data-target="#productQuickModal" asp-controller="Product" asp-action="Modal" asp-route-id="@product.Id"><i class="icon ion-android-open"></i></a></li>
                            </ul>
                            @if (product.DisCountPrice != null && product.DisCountPrice > 0)
                            {
                                <span class="discount-product"> @((((product.Price - product.DisCountPrice) / product.Price) * 100).ToString("#.##")) </span>
                            }
                        </div>
                        <div class="product-content">
                            <ul class="product-rating">
                                <li><i class="fas fa-star"></i></li>
                                <li><i class="fas fa-star"></i></li>
                                <li><i class="fas fa-star"></i></li>
                                <li><i class="fas fa-star"></i></li>
                                <li><i class="fas fa-star"></i></li>
                            </ul>
                            <h4 class="product-title"><a href="single-product.html">@product.Title</a></h4>
                            <div class="product-price">
                                @if (product.DisCountPrice != null && product.DisCountPrice > 0)
                                {
                                    <span class="regular-price ">€@product.Price</span>
                                    <span class="price-sale">€@product.DisCountPrice</span>
                                }
                                else
                                {
                                    <span class="price-sale">€@product.Price</span>
                                }

                            </div>
                        </div>
                    </div> <!-- single product -->
                }

            </div>
        }

    </div>





</div> <!-- product items -->

LastBackProje/LastBackProje/Views/Shared/_PromoCodePartial.cshtml
@model Dictionary<string,string>

<p>@Html.Raw(Model.FirstOrDefault(s=>s.Key=="Promocode").Value)</p>

LastBackProje/LastBackProje/Views/Shared/_searchPartial.cshtml
@model IEnumerable<Product>

    @foreach (Product product in Model)
    {
        <a class="d-block" href="#">
            <li class="d-flex justify-content-between align-items-center">
                <img style="width: 100px;" src="/assets/images/product/@product.MainImage}" />
                <p>@product.Title</p>
                <span class="price-sale">$ @product.Price</span>
            </li>
        </a>
    }